---
--- Events present in the game
---

local events = {
    BRICK_HIT = "BRICK_HIT",
    BRICK_UNBREAKABLE_HIT = "BRICK_UNBREAKABLE_HIT",
    BRICK_DESTROYED = "BRICK_DESTROYED",
    LEVEL_COMPLETED = "LEVEL_COMPLETED",
    HEALTH_DECREASED = "HEALTH_DECREASED",
    GAME_PAUSED_OR_UNPAUSED = "GAME_PAUSED_OR_UNPAUSED",
}

return events